[workspace]
members = [
    "crates/muds",
    "crates/mugl",
    "crates/mugltf",
    "crates/munum"
]
resolver = "2"

[profile.release]
lto = true
opt-level = "z"
strip = "debuginfo"
panic = "abort"
codegen-units = 1
