[package]
name = "munum"
version = "0.1.0"
edition = "2021"
authors = ["Andy K. S. Wong <andykswong@outlook.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/andykswong/munum-rs"
homepage = "https://github.com/andykswong/munum-rs"
documentation = "https://docs.rs/munum"
description = "Rust Micro Library for 3D Math"
categories = ["mathematics", "no-std", "wasm"]
keywords = ["math", "matrix", "3d"]

[dependencies]
cfg-if = "1.0.0"
num = { version = "0.4", default-features = false }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = [
    "num/std"
]
libm = [
    "num/libm"
]
