name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
    - name: Run all-features tests
      run: cargo test --verbose --all-features
    - name: Run no_std tests
      run: cargo test --verbose --no-default-features --features libm,gltf-name
    - name: Run serde tests
      run: cargo test --verbose --features serde
    - name: Run no_std serde tests
      run: cargo test --verbose --no-default-features --features libm,gltf-name,serde

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Run mugltf wasm tests
      working-directory: ./crates/mugltf
      run: wasm-pack test --headless --chrome --all-features
